### ISSUE TITLE
首页的各模块图片应如何选择

### ISSUE THREAD

**Issue by xhd0728** [corpus-web/frontend#1]
有两个想法
- 使用各个模块的轮播图第一张，但是大小比例不对
- 使用旧版网站的那几张固定图片，可能不太合适
望各位提出宝贵建议
@wfloveiu @Daria8976

**Comment by xhd0728** [comment]
![image](https://user-images.githubusercontent.com/77320781/212257415-a30e6cbb-f4f5-4d77-9e27-8e0f949c8942.png)

**Comment by wfloveiu** [comment]
我觉得如果要使用第一个消息的图片的话，像课程建设的消息是没有图片的，不太合适

**Comment by xhd0728** [comment]
> 我觉得如果要使用第一个消息的图片的话，像课程建设的消息是没有图片的，不太合适

不愧是大佬，见解太高明了
